name: Deploy Flutter Web to GH Pages

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.35.1'
          channel: 'stable'

      - name: Enable web
        run: flutter config --enable-web

      - name: Pub get
        run: flutter pub get

      - name: Build web (GitHub Pages)
        env:
          PROXY_BASE: ${{ secrets.PROXY_BASE }}
          LANG: en-US
        run: flutter build web --release --base-href /movies/ --pwa-strategy=none --dart-define=PROXY_BASE=$PROXY_BASE --dart-define=LANG=$LANG

              # si quieres también inyectar el idioma
      - name: Sanity check PROXY_BASE
        run: |
          set -e
          if [ -z "${{ secrets.PROXY_BASE }}" ]; then
            echo "❌ Missing PROXY_BASE secret"; exit 1
          fi
          echo "✅ PROXY_BASE is set"
          curl -s -I "${{ secrets.PROXY_BASE }}/movie/popular?language=en-US&page=1" | head -n1

      - name: Deploy to gh-pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: build/web
          publish_branch: gh-pages
